apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: yossarian-go-tls
  namespace: yossarian-go
spec:
  secretName: yossarian-go-tls
  issuerRef:
    name: my-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
  - yossarian-go.mydomain.local